services:
  - type: web
    name: groqsense-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://groqsense-backend.onrender.com 