index_symbols = {
    "Nifty 50": "^NSEI",
    "Sensex": "^BSESN",
    "Nifty Bank": "^NSEBANK",
    "Nifty IT": "^CNXIT",
    "Nifty Midcap 50": "^NSEMDCP50",
    "Nifty Financial Services": "^CNXFIN",
    "Nifty FMCG": "^CNXFMCG",
    "Nifty Pharma": "^CNXPHARMA",
    "Nifty PSU Bank": "^CNXPSUBANK",
    "Nifty Auto": "^CNXAUTO",
    "Nifty Energy": "^CNXENERGY",
    "Nifty Infra": "^CNXINFRA",
    "Nifty Metal": "^CNXMETAL",
    "Nifty Realty": "^CNXREALTY",
    "Nifty Media": "^CNXMEDIA",
    "Nifty Private Bank": "^NIFTYPRBANK",
    "Nifty Healthcare": "^CNXHEALTH",
    "Nifty Services Sector": "^NIFTYSERVICE",
    "Nifty 100": "^CNX100",
    "Nifty 200": "^CNX200",
    "Nifty 500": "^CNX500",
    "Nifty Midcap 100": "^NIFMIDCAP100",
    "Nifty Smallcap 100": "^CNXSCAP",
    "Nifty Next 50": "^NSENXT50",
    "Nifty Commodities": "^CNXCOMMODITIES"
}
